// Single source of truth for all portfolio content. Every claim here is from real client work.
export const projects = [
  {
    slug: 'sopbot', title: 'SOPBot + WorkflowIQ', client: 'DadaAI (Digital Dada Consulting)', region: 'New York, US', year: '2026',
    role: 'AI Developer', platform: 'Voice AI · Web · Google Workspace', status: 'Live', live: 'https://thesopbot.com', liveLabel: 'thesopbot.com',
    tags: 'agents rag auto', chips: ['Voice AI', 'LLM pipelines', 'Google Docs API', 'Process intelligence'],
    oneLine: 'Call a number, describe how you work, and get a finished, structured SOP. WorkflowIQ then tells you which processes to automate first.',
    card: 'Voice-to-SOP engine plus an automation-opportunity scorer, now live for teams.',
    kpis: [['Live', 'in production'], ['2', 'products shipped'], ['1', 'call to a finished SOP']],
    brief: [
      'Most companies run on <strong>tribal knowledge</strong>: processes that live in people\'s heads and leave when they do. Writing SOPs is slow, so nobody writes them, and automation projects stall because nobody can see which processes are worth automating.',
      'DadaAI wanted a product that would turn that knowledge into a <strong>real process library</strong> with almost no effort from the team, and then turn the library into a data-backed automation roadmap.'],
    challenges: ['Spoken explanations are messy: people jump between steps, skip context and mention tools in passing.', 'Every SOP had to follow the same rigorous structure (purpose, trigger, tools, steps, edge cases, completion criteria) to be usable.', 'Automation recommendations had to be ranked and defensible, not a generic list of AI ideas.'],
    features: [['phone', 'Phone-in capture', 'Teams call a dedicated number and simply talk. No forms and no writing.'], ['cpu', 'LLM structuring', 'A transcription and LLM pipeline extracts triggers, tools, steps, edge cases and completion criteria.'], ['doc', 'Docs that just appear', 'Finished SOPs are written straight into Google Docs and collected in a central dashboard.'], ['chart', 'WorkflowIQ scoring', 'Each process is scored for inefficiency and ranked by impact and time saved.'], ['map', 'Executive outputs', 'Optimisation tables, flowcharts and executive summaries leadership can act on.'], ['wrench', 'Tool recommendations', 'Each opportunity is mapped to a specific automation tool.']],
    arch: [['Capture', [['Phone line', 'voice call'], ['Transcription', 'speech-to-text']]], ['Intelligence', [['LLM structuring', 'schema-bound extraction', 'hl'], ['Edge-case detection', 'gaps + exceptions']]], ['Delivery', [['Google Docs API', 'SOP document'], ['Dashboard', 'process library']]], ['WorkflowIQ', [['Scoring engine', 'impact × time', 'mint'], ['Reports', 'tables · flowcharts · summaries']]]],
    archCaption: 'Speech in, structured knowledge out. The same process library then drives the automation roadmap.',
    decisions: [['Schema-first extraction', 'Rather than asking the model for "an SOP", every call is forced into a fixed schema, so thousands of SOPs share one reliable structure that is searchable and comparable.'], ['Voice as the interface', 'The biggest barrier to documentation is effort. Letting people talk removes it and captures detail that a written form never would.'], ['Scoring before automating', 'WorkflowIQ ranks processes by impact and time saved before any build starts, so clients spend automation budget where it returns most.']],
    outcomes: [['Live', 'product at thesopbot.com'], ['6', 'structured fields per SOP step set'], ['0', 'forms or writing required'], ['2', 'connected products']],
    stack: ['LLM APIs', 'Speech-to-text', 'Python', 'Google Workspace APIs', 'Next.js', 'Supabase', 'n8n'],
  },
  {
    slug: 'exotic-lobby', title: 'Exotic Lobby', client: 'Exotic Lobby', region: 'Dubai, UAE · Europe · US', year: '2026',
    role: 'Sole developer, end to end', platform: 'iOS · Android · Web', status: 'Live', live: 'https://exoticlobby.com', liveLabel: 'exoticlobby.com',
    tags: 'product', chips: ['React Native', 'TypeScript', 'Supabase', 'Realtime', 'Mapbox'],
    oneLine: 'A private social network for hypercar collectors across three continents. I designed, built and shipped the iOS app, Android app and web platform on my own.',
    card: 'Private hypercar network: iOS, Android and web, built solo from architecture to launch.',
    kpis: [['3', 'platforms shipped solo'], ['80%', 'lighter media payload'], ['3', 'continents of members']],
    brief: [
      'Exotic Lobby is an invitation-only community for owners of the world\'s rarest cars: Ferraris, McLarens, Lamborghinis and Porsches, with members across <strong>Europe, the Middle East and the US</strong>.',
      'The client needed a premium product that felt worthy of its members: live convoys, private chat, events, garages and service booking. They also needed one engineer who could own <strong>everything from architecture to App Store delivery</strong>.'],
    challenges: ['Real-time location for moving convoys, with chat, had to stay reliable on mobile networks across countries.', 'A third-party CDN was failing for international members, and heavy media was breaking the experience.', 'Different permissions were needed for members, community leaders and global admins, enforced at the database level.'],
    features: [['pin', 'Live convoy tracking', 'Real-time location of every car in a drive on interactive Mapbox maps.'], ['chat', 'Convoy chat', 'Group messaging over WebSockets while driving together.'], ['flag', 'Community events', 'Drives, dinners and track days with RSVPs and details.'], ['car', 'Digital garages', 'Members showcase their collections and manage each car.'], ['wrench', 'Service booking', 'Book maintenance directly from the car\'s profile.'], ['shield', 'Admin dashboards', 'Role-based control for community leaders and global admins.']],
    arch: [['Clients', [['iOS app', 'React Native'], ['Android app', 'React Native'], ['Web platform', 'TypeScript']]], ['Realtime', [['Supabase Edge Functions', 'business logic', 'hl'], ['WebSockets', 'location + chat']]], ['Data', [['PostgreSQL', 'row-level security', 'mint'], ['Supabase Storage', 'owned media']]], ['Services', [['Mapbox', 'maps + routes'], ['Admin', 'roles + moderation']]]],
    archCaption: 'One TypeScript codebase across iOS, Android and web, with security enforced in Postgres rather than in the app.',
    decisions: [['Security in the database', 'Row-level security policies in PostgreSQL mean a member can never read another member\'s private data, even if the client app is compromised.'], ['Owning the media pipeline', 'I migrated 79 assets off a failing third-party CDN to Supabase storage, cutting payload from 68 MB to 14 MB and fixing access for international members.'], ['One codebase, three platforms', 'React Native plus TypeScript let a single engineer ship and maintain iOS, Android and web without the quality gaps that usually come with that.']],
    outcomes: [['80%', 'smaller media payload (68 → 14 MB)'], ['79', 'assets migrated to owned storage'], ['3', 'platforms: iOS, Android, web'], ['1', 'engineer, end to end']],
    stack: ['React Native', 'TypeScript', 'Supabase', 'PostgreSQL + RLS', 'Edge Functions', 'WebSockets', 'Mapbox'],
  },
  {
    slug: 'yourinboxhero', title: 'YourInboxHero', client: 'YourInboxHero', region: 'SaaS · Small businesses', year: '2026',
    role: 'Full-stack developer, end to end', platform: 'Web · SaaS · API', status: 'Live', live: 'https://www.yourinboxhero.com/', liveLabel: 'yourinboxhero.com',
    tags: 'product auto', chips: ['FastAPI', 'React 19', 'PostgreSQL', 'Stripe', 'Docker'],
    oneLine: 'Automated invoice reminders and payment chasing for small businesses. Add an invoice once and the system escalates from email to SMS to voice calls until it is paid.',
    card: 'Invoice follow-up SaaS: multi-channel reminders, Stripe billing and plan-gated access, built solo.',
    kpis: [['3', 'reminder channels: email, SMS, voice'], ['109+', 'automated backend tests'], ['3', 'paid plan tiers']],
    brief: [
      'Small businesses lose time and cash chasing clients for overdue payments. YourInboxHero helps them <strong>get paid faster</strong> by automating the whole invoice follow-up process: owners add their invoices once, and reminders escalate on their own as invoices move from upcoming to overdue.',
      'Reminders go out by <strong>email, then SMS, then voice calls</strong>, with safeguards that stop automatically the moment an invoice is paid. I built the product end to end, from the API and billing to the dashboard and production deployment.'],
    challenges: ['Reminders had to escalate across three channels on configurable timing rules, and stop reliably once an invoice was paid.', 'Access had to be locked to active paid subscriptions, with plan limits enforced on every path that can send a reminder.', 'The live database had drifted from its migration history after being partly bootstrapped outside migrations, and production data had to move from SQLite to PostgreSQL safely.'],
    features: [['clock', 'Automated multi-channel reminders', 'A daily scheduler escalates reminders from email to SMS to voice calls based on configurable timing rules, with usage tracked per channel for every invoice.'], ['lock', 'Subscription-gated access', 'Starter, Growth and Scale tiers, each with its own monthly reminder quota and features. No one can register or use the product without an active paid plan.'], ['trend', 'Usage enforcement', 'Hard stops when a plan\'s monthly quota is reached, with automated warning emails at 80% and 100% so customers are never surprised.'], ['card', 'Stripe billing', 'Checkout sessions and webhook-driven subscription lifecycle: activation, renewal, payment failure and recovery, and cancellation.'], ['doc', 'Branded invoice PDFs', 'Custom invoice PDFs with configurable branding and logo for each business.'], ['building', 'Multi-tenant by design', 'Every business\'s debtors, invoices and templates are scoped and isolated per account.'], ['key', 'Test access tooling', 'HMAC-verified invite codes grant test access without manual per-user admin changes.'], ['clip', 'Document requests', 'Clients can be sent secure upload links to collect documents.']],
    arch: [['Frontend', [['React 19 + TypeScript', 'dashboard on Vercel'], ['React Router + Vite', 'SPA routing']]], ['API', [['FastAPI', 'Python services', 'hl'], ['Plan gating', 'plan_features.py']]], ['Automation', [['APScheduler', 'daily sweeps + locking', 'mint'], ['Resend · GoHighLevel', 'email · SMS · voice']]], ['Data & billing', [['PostgreSQL', 'SQLAlchemy + Alembic'], ['Stripe', 'signed webhooks']]]],
    archCaption: 'Dockerized backend on a Hetzner VPS behind Caddy for automatic HTTPS, with the React frontend deployed on Vercel.',
    decisions: [['One gate for every send path', 'Plan entitlements live in a single module that the API routes, the scheduler and the email service all enforce, so no single code path can bypass a plan limit.'], ['Atomic, race-safe usage counting', 'Reminder usage is counted with keyed SQL UPDATE statements rather than mutating ORM objects, so counts stay correct across concurrent request-scoped sessions.'], ['Webhooks as the only way in', 'Access is granted only by signature-verified Stripe webhooks. Nothing on the client can activate a subscription.'], ['Fixing schema drift properly', 'I found the live database had diverged from the Alembic history and wrote a corrective migration, so new environments deploy with a guaranteed-correct schema.']],
    outcomes: [['3', 'channels escalated automatically'], ['109+', 'tests gating deploys'], ['0', 'data loss moving SQLite to PostgreSQL'], ['1', 'engineer, end to end']],
    stack: ['Python', 'FastAPI', 'SQLAlchemy', 'Alembic', 'APScheduler', 'React 19', 'TypeScript', 'Vite', 'PostgreSQL', 'Stripe', 'Resend', 'GoHighLevel', 'Docker', 'Caddy', 'Vercel'],
  },
  {
    slug: 'agent-os', title: 'Private AI Operating System', client: 'Film director (private client)', region: 'Europe · Dubai', year: '2026',
    role: 'AI Consultant, architect and trainer', platform: 'Local-first · n8n · Docker · Ollama', status: 'Handed over',
    tags: 'agents auto consult', chips: ['Multi-agent', 'Intent routing', 'Ollama', 'n8n', 'Docker'],
    oneLine: 'An 11-agent AI system for a film director whose work could never touch a public AI tool. It runs entirely on their own machine, and they operate it themselves.',
    card: '11-agent local-first system with an intent router, built for a film director and handed over.',
    kpis: [['11', 'coordinated agents'], ['100%', 'local inference'], ['0', 'data sent to public AI']],
    brief: [
      'A film director wanted the leverage of AI agents across their creative and operational work, but <strong>unreleased scripts, contracts and schedules</strong> could not be sent to public AI services.',
      'The brief: a private AI system that behaves like a coordinated team, runs <strong>entirely on local hardware</strong>, and that the director can run and extend without me.'],
    challenges: ['Confidential creative material meant no cloud LLMs at all.', 'Many specialised tasks needed a reliable way to route each request to the right agent.', 'The client is not technical, so success meant full independence after handover.'],
    features: [['compass', 'Master intent router', 'One orchestrator understands each request and routes it to the right specialist agent.'], ['bot', '10 specialist agents', 'Each agent owns a domain of the director\'s work, with its own tools and memory.'], ['lock', 'Per-agent access control', 'Every agent sees only the data it needs, nothing more.'], ['laptop', 'Local-first inference', 'Open models on Ollama. Nothing leaves the machine.'], ['box', 'Containerised', 'The whole system runs in Docker for one-command start and recovery.'], ['grad', 'Owner training', 'Hands-on training so the client runs and extends it on their own.']],
    arch: [['Input', [['Director request', 'chat / voice / file']]], ['Orchestration', [['Master intent router', 'classify + dispatch', 'hl'], ['Access policies', 'per-agent scopes']]], ['Agents', [['10 specialist agents', 'n8n workflows'], ['Tools', 'docs · calendar · files']]], ['Runtime', [['Ollama', 'local LLMs', 'mint'], ['Docker', 'isolated services']]]],
    archCaption: 'Agent roles shown are illustrative; the client\'s specifics are confidential.',
    decisions: [['Router before agents', 'A single intent router makes behaviour predictable: every request has one owner, which stops agents looping and makes failures easy to trace.'], ['Least-privilege agents', 'Each agent has its own access scope, so a research agent can never read contracts, for example. Governance is built into the design.'], ['Designed for handover', 'Every workflow is visual in n8n, and I trained the director on it, so the system doesn\'t depend on me.']],
    outcomes: [['11', 'agents (1 orchestrator + 10)'], ['0', 'bytes sent to public AI'], ['1', 'command to start (Docker)'], ['100%', 'client-operated after training']],
    stack: ['n8n', 'Ollama', 'Docker', 'Local LLMs', 'Intent routing', 'Access control'],
  },
  {
    slug: 'goecoach', title: 'GoeCoach', client: 'DadaAI (Digital Dada Consulting)', region: 'New York, US', year: '2026',
    role: 'Architect and full-stack AI engineer', platform: 'SMS · Web · API', status: 'Live',
    tags: 'rag product agents', chips: ['Next.js', 'FastAPI', 'Multi-LLM', 'pgvector', 'Twilio'],
    oneLine: 'An AI executive coach for US founders that lives in their text messages. No app, no login, and answers in under half a second.',
    card: 'SMS-first AI executive coach for US founders with sub-500 ms RAG.',
    kpis: [['<500ms', 'RAG response'], ['448+', 'automated interactions'], ['14', 'workflows migrated']],
    brief: [
      'Founders don\'t open coaching apps. They do answer texts. DadaAI wanted a coach that meets executives <strong>where they already are</strong>, remembers every commitment and follows up relentlessly.',
      'I architected and launched the platform, and later rescued its automation layer by migrating it off a fragile vendor dependency <strong>with zero downtime</strong>.'],
    challenges: ['Answers had to feel instant over SMS while drawing on each founder\'s full history.', 'The automation backbone depended on 43 Airtable nodes across 14 workflows and was becoming unstable.', 'Email, SMS and voice had to work as one coaching experience.'],
    features: [['chat', 'SMS-first coaching', 'Daily check-ins, accountability and reflection over plain text.'], ['cpu', 'Long-term memory', 'RAG over each founder\'s goals, history and commitments.'], ['zap', 'Sub-500 ms retrieval', 'pgvector HNSW index behind a Redis cache.'], ['shuffle', 'Multi-LLM router', 'GPT-4, Claude and Gemini, each used for what it does best.'], ['mail', 'Omnichannel', 'Email, SMS and voice touchpoints in one flow.'], ['layers', 'Zero-downtime migration', 'Airtable to Supabase migration with no interruption to users.']],
    arch: [['Channels', [['SMS', 'Twilio'], ['Email + voice', 'automations']]], ['API', [['FastAPI', 'Python services', 'hl'], ['Model router', 'GPT-4 · Claude · Gemini']]], ['Memory', [['Redis cache', 'hot answers', 'mint'], ['pgvector HNSW', 'semantic recall']]], ['Platform', [['Next.js', 'web app'], ['Supabase', 'data + workflows']]]],
    archCaption: 'The cache answers first and vector search second, which keeps coaching replies under 500 ms.',
    decisions: [['Cache in front of vectors', 'Redis serves frequent context instantly and pgvector HNSW handles semantic recall, so retrieval stays under 500 ms.'], ['Removing a single point of failure', 'I migrated 43 Airtable nodes across 14 production workflows to Supabase with zero downtime, stabilising 448+ automated client interactions.'], ['Right model per task', 'A router picks GPT-4, Claude or Gemini per task, balancing quality, latency and cost.']],
    outcomes: [['<500ms', 'RAG response time'], ['448+', 'automated client interactions'], ['43', 'Airtable nodes migrated'], ['0', 'downtime during migration']],
    stack: ['Next.js', 'Python', 'FastAPI', 'Supabase', 'pgvector', 'Redis', 'OpenAI', 'Claude', 'Gemini', 'Twilio'],
  },
  {
    slug: 'voice-agent', title: 'Autonomous Voice Sales Agent', client: 'DadaAI (Digital Dada Consulting)', region: 'New York, US', year: '2026',
    role: 'AI Developer', platform: 'Voice AI · CRM', status: 'Deployed',
    tags: 'agents auto', chips: ['Vapi', 'Voice AI', 'LLM classification', 'CRM'],
    oneLine: 'AI voice agents that call leads, hold a real conversation and book the meeting before hanging up, within US calling compliance rules.',
    card: 'Outbound AI voice agents that book meetings mid-call; 100+ leads enriched daily.',
    kpis: [['100+', 'leads enriched daily'], ['TCPA', 'compliant flows'], ['Mid-call', 'booking']],
    brief: ['Outbound sales teams spend most of their time dialling people who don\'t answer. The goal was an <strong>autonomous pipeline</strong> that enriches leads, calls them, qualifies them and books meetings with no human in the loop, while staying <strong>TCPA-compliant</strong>.'],
    challenges: ['Calls had to sound natural and handle objections in real time.', 'US calling regulations (TCPA) required consent-aware dialling.', 'Leads had to be prioritised before any call was placed.'],
    features: [['database', 'Lead enrichment', '100+ B2B leads enriched every day.'], ['cpu', 'Sentiment classification', 'An LLM scores intent and sentiment from each conversation.'], ['phone', 'Natural voice calls', 'Vapi voice agents handle the full conversation.'], ['calendar', 'Mid-call booking', 'The agent checks the calendar and books the meeting on the spot.'], ['scale', 'TCPA compliance', 'Consent-aware calling flows.'], ['refresh', 'CRM sync', 'Every outcome is logged back automatically.']],
    arch: [['Leads', [['Lead sources', 'B2B lists'], ['Enrichment', 'data + scoring']]], ['Decision', [['LLM classifier', 'intent + sentiment', 'hl']]], ['Conversation', [['Vapi voice agent', 'live call', 'mint'], ['Calendar', 'mid-call booking']]], ['System of record', [['CRM', 'outcomes + notes']]]],
    archCaption: 'From a raw lead to a booked meeting with no human handoff.',
    decisions: [['Score before dialling', 'LLM enrichment and classification mean agents call the most promising leads first.'], ['Book during the call', 'Booking while the prospect is still on the line removes the drop-off of follow-up emails.'], ['Compliance by design', 'TCPA rules are built into the calling flow rather than left to operators.']],
    outcomes: [['100+', 'leads enriched per day'], ['Mid-call', 'meeting booking'], ['TCPA', 'compliant calling'], ['0', 'human handoffs needed']],
    stack: ['Vapi', 'LLM APIs', 'n8n', 'CRM integration', 'Calendar APIs'],
  },
  {
    slug: 'welfare-hr', title: 'AI HR Operations Blueprint', client: 'Welfare group (private client)', region: 'Dubai, UAE', year: '2026',
    role: 'AI Consultant and trainer', platform: 'Automation blueprint · Training', status: 'Handed over',
    tags: 'auto consult', chips: ['AI automation', 'HR operations', 'Human in the loop', 'Team training'],
    oneLine: 'Blueprints that automate HR from CV screening to onboarding for a Dubai welfare group, plus the coaching their team needed to own it.',
    card: 'End-to-end AI blueprint for HR (screening to onboarding) and team enablement in Dubai.',
    kpis: [['4', 'HR stages automated'], ['100%', 'team-owned after handover'], ['HITL', 'approval checkpoints']],
    brief: ['A Dubai welfare group\'s HR team was buried in manual screening, scheduling and onboarding. They needed a clear, safe plan to bring AI into the workflow, with <strong>people keeping the final say</strong>, and a team able to run it afterwards.'],
    challenges: ['Hiring decisions are sensitive, so AI had to assist rather than decide.', 'The team had little prior exposure to AI or automation tools.', 'The blueprint had to be practical to maintain in-house.'],
    features: [['doc', 'AI screening', 'CV parsing, scoring and role-fit summaries.'], ['calendar', 'Auto scheduling', 'Interview slots offered and confirmed automatically.'], ['pen', 'Offer drafting', 'Letters generated from templates and candidate data.'], ['briefcase', 'Onboarding flows', 'Welcome packs, document checklists and reminders.'], ['checkc', 'Human checkpoints', 'HR approves every shortlist and offer.'], ['grad', 'Team coaching', 'Hands-on sessions so the team owns the system.']],
    arch: [['Intake', [['Applications', 'CVs + forms']]], ['AI assist', [['Screening', 'parse + score', 'hl'], ['Summaries', 'role fit']]], ['Human', [['HR approval', 'shortlist + offer', 'mint']]], ['Automation', [['Scheduling', 'calendar'], ['Onboarding', 'packs + reminders']]]],
    archCaption: 'AI handles the repetitive work and people make the decisions.',
    decisions: [['Assist, don\'t decide', 'Every AI step in a hiring decision ends at a human approval, which protects fairness and keeps accountability with the team.'], ['Blueprint first', 'A complete written blueprint let leadership see the full workflow before anything was built.'], ['Enablement as a deliverable', 'Coaching the internal team was part of the scope, so the organisation owns the system rather than renting a consultant.']],
    outcomes: [['4', 'HR stages covered'], ['HITL', 'on every decision'], ['100%', 'owned by the internal team'], ['1', 'unified blueprint']],
    stack: ['LLM APIs', 'n8n / Make', 'Calendar APIs', 'Document automation'],
  },
  {
    slug: 'levelup', title: 'LevelUp Northeast 2026', client: 'SporTech Innovation Lab for CII and IDGS', region: 'India', year: '2026',
    role: 'AI Developer Intern (delivery lead on portal)', platform: 'Web · Azure', status: 'Delivered',
    tags: 'product rag', chips: ['React', 'Azure', 'Node.js', 'Qdrant', 'Gemini'],
    oneLine: 'The national registration portal for an event run with the Confederation of Indian Industry. 5,000+ users and zero data corruption on launch day.',
    card: 'National event portal (CII / IDGS): 5,000+ users on launch day, zero corrupted records.',
    kpis: [['5,000+', 'users on launch day'], ['0', 'corrupted records'], ['<500ms', 'two-tier search']],
    brief: ['LevelUp Northeast 2026 was organised with the <strong>Confederation of Indian Industry (CII)</strong> and the Indian Digital Gaming Society (IDGS). Registration day would bring thousands of users at once, and bulk athlete data arrived as messy CSV files.'],
    challenges: ['A launch-day traffic spike could not be allowed to corrupt a single record.', 'Bulk CSV imports contained malformed rows and duplicates.', 'Certificates needed stable, collision-free IDs.'],
    features: [['pen', 'Registration portal', 'React and Tailwind, deployed to Vercel and Azure Container Apps.'], ['inbox', 'Fault-tolerant ingestion', 'Node.js CSV engine with concurrency control and dry-run validation.'], ['wrench', 'Row recovery', 'Malformed rows are recovered instead of being dropped.'], ['hash', 'Deterministic IDs', '64-bit certificate IDs that never collide.'], ['search', 'Two-tier RAG search', 'Postgres tsvector + pgvector, with a Qdrant and Gemini fallback.'], ['activity', 'Scrum delivery', 'Delivered in sprints using Jira and Confluence.']],
    arch: [['Frontend', [['React + Tailwind', 'Vercel']]], ['Backend', [['Node.js ingestion', 'locks + dry run', 'hl'], ['Azure Container Apps', 'services']]], ['Search', [['tsvector + pgvector', 'tier 1', 'mint'], ['FastAPI · Qdrant · Gemini', 'tier 2 fallback']]], ['Output', [['Certificates', '64-bit IDs']]]],
    archCaption: 'Validation happens before anything is written, so launch day never produced a bad row.',
    decisions: [['Dry run before commit', 'Every import is validated first, and only clean, reconciled data is committed.'], ['Concurrency control', 'Locks on write paths kept the traffic spike from corrupting records.'], ['Tiered retrieval', 'Cheap keyword and vector search answers most queries, and deep RAG runs only when needed.']],
    outcomes: [['5,000+', 'users served'], ['0', 'data corruption on launch day'], ['64-bit', 'deterministic certificate IDs'], ['<500ms', 'search response']],
    stack: ['React', 'Tailwind CSS', 'Node.js', 'Azure Container Apps', 'Vercel', 'PostgreSQL', 'pgvector', 'Qdrant', 'Gemini', 'FastAPI'],
  },
  {
    slug: 'selvenza', title: 'Selvenza', client: 'Infosoft LLC', region: 'Colorado Springs, US', year: '2025',
    role: 'Software Developer Intern (creator)', platform: 'Developer tooling · CI/CD', status: 'Delivered',
    tags: 'product auto', chips: ['Node.js', 'DOM diffing', 'Docker', 'GitHub Actions'],
    oneLine: 'A self-healing test tool that notices when the UI changes and repairs the broken tests before they break the build.',
    card: 'Self-healing UI tests: detects selector drift and refactors tests, saving 40+ QA hours per release.',
    kpis: [['40+', 'QA hours saved per release'], ['CI/CD', 'native'], ['Auto', 'test refactoring']],
    brief: ['Every UI change at Infosoft broke end-to-end tests, and QA spent days per release chasing selectors instead of finding real bugs. I created Selvenza to <strong>detect and heal selector drift automatically</strong>.'],
    challenges: ['UI refactors silently broke test selectors in React and Vite apps.', 'Repairs had to be accurate enough to trust in CI.', 'Test environments were inconsistent between machines.'],
    features: [['compare', 'DOM snapshot diffing', 'Compares UI snapshots to detect exactly what moved.'], ['activity', 'Selector healing', 'Suggests and applies robust replacement selectors.'], ['refresh', 'Test refactoring', 'Updates test files automatically.'], ['plug', 'REST config API', 'Configuration and reporting over REST.'], ['gauge', 'GitHub Actions', 'Runs on every pull request.'], ['box', 'Docker environments', 'Identical test runs everywhere.']],
    arch: [['Trigger', [['Pull request', 'GitHub Actions']]], ['Detection', [['DOM snapshots', 'before / after', 'hl'], ['Diff engine', 'selector drift']]], ['Healing', [['Selector matcher', 'role · text · position', 'mint'], ['Test refactor', 'auto-commit']]], ['Report', [['Node.js backend', 'REST + dashboards']]]],
    archCaption: 'Drift is caught and fixed on every pull request, before it reaches QA.',
    decisions: [['Semantic matching', 'Replacement selectors are matched by role, text and position, not brittle IDs, so healed tests keep working.'], ['Built into CI', 'Running on every PR means drift is fixed while the change is still fresh.'], ['Reproducible runs', 'Docker gives every run an identical environment and removes "works on my machine" failures.']],
    outcomes: [['40+', 'QA hours saved per release'], ['Every PR', 'drift detection'], ['Auto', 'test refactoring'], ['Docker', 'reproducible runs']],
    stack: ['Node.js', 'React / Vite', 'DOM diffing', 'REST APIs', 'Docker', 'GitHub Actions'],
  },
  {
    slug: 'a-square-merch', title: 'A Square Merch', client: 'Self-initiated build (fictional manufacturer)', region: 'India', year: '2026',
    role: 'Sole developer, end to end', platform: 'Web · CMS · Admin panel', status: 'Live', live: 'https://a-square-psi.vercel.app/', liveLabel: 'a-square-psi.vercel.app',
    tags: 'product', chips: ['Next.js 16', 'Prisma', 'Supabase Postgres', 'GSAP', 'NextAuth'],
    oneLine: 'A full-stack B2B apparel manufacturing site built to turn cold traffic into qualified RFQs, not to sell single units. Next.js, Postgres and an admin CMS, all built solo.',
    card: 'B2B apparel manufacturer site with an RFQ pipeline, admin CMS and hand-built UI patterns.',
    kpis: [['18', 'product categories'], ['13', 'customization techniques'], ['13', 'Postgres models']],
    brief: [
      'A factory website has a different job from a storefront: it has to turn cold traffic into a <strong>qualified request for quote</strong>. A Square Merch is a fictional India-based manufacturer serving streetwear brands, corporate buyers and export clients, and I built the whole site as a self-initiated project.',
      'The brief I set was explicit: <strong>do not think like a normal designer</strong>. That ruled out component-library defaults, so the carousel, the techniques accordion and the lookbook-style product grid are all built from scratch.'],
    challenges: ['Eighteen categories, eleven fabrics, thirteen techniques and thirteen industries all had to be editable from an admin panel and served from a real database.', 'A pinned, scroll-driven cinematic intro had to cooperate with a smooth-scroll library that owns the scroll position.', 'Static generation of about 56 routes exhausted a free-tier Postgres connection pooler during builds.'],
    features: [['layers', '3D coverflow catalogue', 'A custom carousel for browsing the eighteen product categories.'], ['film', 'Cinematic scroll intro', 'GSAP ScrollTrigger intro, gated behind prefers-reduced-motion.'], ['inbox', 'Multi-step RFQ form', 'react-hook-form and Zod, with honeypot filtering and server-side validation.'], ['database', 'Admin CMS', 'Role-gated editing of products, fabrics, blog, leads, testimonials and FAQs.'], ['shield', 'Hardened endpoints', 'Every admin route checks the session and role before touching the database.'], ['box', 'Durable file storage', 'Tech-pack uploads go to Vercel Blob in production, renamed to a fresh UUID.']],
    arch: [['Public site', [['Next.js App Router', '20+ server-rendered routes'], ['Custom UI', 'GSAP · Framer Motion · Lenis', 'hl']]], ['API', [['Quotes endpoint', 'rate-limited + Zod', 'mint'], ['Admin routes', 'requireAdmin() guard']]], ['Data', [['lib/data.ts', 'rows to UI shapes'], ['Prisma + Postgres', 'Supabase pooler']]], ['Storage', [['Vercel Blob', 'tech packs + media']]]],
    archCaption: 'Pages never see storage details: one data layer turns database rows back into the shapes the UI expects.',
    decisions: [['JSON-text list fields', 'Lists are stored as JSON text rather than native arrays, so moving from SQLite in development to Postgres in production was a one-line provider change instead of a migration.'], ['Lenis owns the scroll', 'The intro hand-off goes through lenis.scrollTo() rather than the native API, so the library and the visible scroll position never disagree.'], ['Server-side validation', 'Rate limiting, honeypot filtering and Zod run on the server, because client-side validation is UX and not security.']],
    outcomes: [['18', 'product categories, DB-driven'], ['13', 'Prisma models'], ['~56', 'statically generated routes'], ['9', 'admin routes, all guarded']],
    stack: ['Next.js 16', 'TypeScript', 'PostgreSQL (Supabase)', 'Prisma', 'NextAuth', 'GSAP', 'Framer Motion', 'Lenis', 'Tailwind CSS', 'Vercel Blob'],
  },
];

export const flagship = ['sopbot', 'exotic-lobby', 'yourinboxhero'];

export const certs = [
  // [issuer, title, image-slug or '', tags]
  ['Oracle', 'OCI Certified Generative AI Professional', '', 'ai'],
  ['Oracle', 'OCI Certified Data Science Professional', 'oracle-oci-data-science', 'ai data'],
  ['Stanford Online', 'Advanced Learning Algorithms', 'stanford-advanced-algorithms', 'ai'],
  ['Google', 'Gemini Multimodality & Multimodal RAG', 'google-gemini-multimodal-rag', 'ai'],
  ['Google', 'Responsible AI: Fairness & Bias', 'google-responsible-ai', 'ai'],
  ['Google', 'Transformer Models and BERT', 'google-transformer-bert', 'ai'],
  ['Google', 'Encoder-Decoder Architecture', 'google-encoder-decoder', 'ai'],
  ['Google', 'Attention Mechanism', 'google-attention', 'ai'],
  ['Google', 'Create Image Captioning Models', 'google-image-captioning', 'ai'],
  ['Google', 'Vertex AI Studio', 'google-vertex-ai-studio', 'ai cloud'],
  ['Google', 'Vector Search and Embeddings', 'google-vector-search', 'ai'],
  ['Google Cloud', 'Introduction to Generative AI', 'google-intro-genai', 'ai'],
  ['Google', 'Google Analytics Certification', 'google-analytics', 'data'],
  ['Google', 'Project Management', 'google-project-management', 'business'],
  ['Imperial College London', 'Creative Thinking: Techniques and Tools', 'imperial-creative-thinking', 'business'],
  ['IBM', 'Machine Learning with Python (Honors)', 'ibm-machine-learning', 'ai'],
  ['IBM', 'SQL and Relational Databases 101', 'ibm-sql', 'data'],
  ['Microsoft', 'Develop Generative AI Solutions with Azure', 'microsoft-azure-genai', 'ai cloud'],
  ['Microsoft', 'Power Platform Solutions with AI', 'microsoft-power-platform-ai', 'ai'],
  ['Microsoft', 'GitHub Copilot Fundamentals', 'microsoft-github-copilot', 'ai'],
  ['Microsoft · LinkedIn', 'Career Essentials in Data Analysis', 'microsoft-data-analysis', 'data'],
  ['DeepLearning.AI · AWS', 'Generative AI with Large Language Models', 'deeplearning-genai-llms', 'ai'],
  ['LinkedIn', 'Generative AI: Working with LLMs', 'linkedin-genai-llms', 'ai'],
  ['Udemy', 'Fine-Tuning LLMs: Beginner to Advanced', 'finetuning-llms', 'ai'],
  ['AWS', 'Exam Readiness: ML Specialty', 'aws-ml-specialty-readiness', 'ai cloud'],
  ['AWS', 'Knowledge: Architecting', 'aws-architecting', 'cloud'],
  ['AWS', 'Building RAG Applications', 'aws-rag', 'ai cloud'],
  ['MongoDB', 'Vector Search for Semantic Search', 'mongodb-vector-search', 'ai data'],
  ['MongoDB', 'Introduction to AI and Vector Search', 'mongodb-ai-vector', 'ai data'],
  ['Cisco', 'Python Essentials 2', 'cisco-python', 'data'],
  ['WHO', 'Go.Data Dashboards with Power BI', 'who-godata-powerbi', 'data'],
  ['HP', 'Data Science', 'hp-data-science', 'data'],
  ['freeCodeCamp', 'Machine Learning with Python', 'fcc-ml-python', 'ai'],
  ['ISRO', 'ISRO Certification', 'isro', 'business'],
  ['Goldman Sachs · Forage', 'Job Simulation', 'goldman-sachs-forage', 'business'],
  ['Walmart · Forage', 'Job Simulation', 'walmart-forage', 'business'],
  ['PepsiCo', 'Sales Star: Top 1% of 35,000+', 'pepsico', 'business'],
  ['MLOps', 'MLOps Certification', 'mlops', 'ai cloud'],
];
export const moreCerts = [
  ['BCG', 'Data Science Job Simulation'], ['Google', 'Introduction to Image Generation'], ['Google', 'Foundations of Project Management'], ['Google', 'Project Initiation'],
  ['McKinsey', 'Forward Program'], ['PMI', 'Generative AI Overview for Project Managers'], ['LinkedIn', 'Introduction to AI Governance'], ['IBM', 'Introduction to Intelligent Virtual Agents (Watson)'],
  ['Microsoft', 'Power BI Data Analyst'], ['ADBI', 'AI for Social Impact'], ['MathWorks', 'MATLAB Onramp'], ['Infosys Springboard', 'Course Completion'],
];

// What I personally owned on each engagement (shown on case-study pages)
export const owned = {
  sopbot: ['Product flow from phone call to finished Google Doc', 'LLM prompt and schema design for SOP structure', 'Transcription and extraction pipeline', 'Google Workspace integration and document generation', 'WorkflowIQ scoring logic and report outputs', 'Dashboard and process library'],
  'exotic-lobby': ['Discovery and feature scoping with the client', 'App architecture across iOS, Android and web', 'Database schema and row-level security policies', 'Realtime location, chat and events', 'Media pipeline migration and performance', 'Admin dashboards, deployment and domain handover'],
  yourinboxhero: ['Backend API, data model and automation engine', 'Stripe billing and webhook-driven subscription lifecycle', 'Plan-tier feature gating and usage enforcement', 'React frontend and customer dashboard', 'PostgreSQL migration and schema-drift fix', 'Dockerized deployment on Hetzner behind Caddy, frontend on Vercel'],
  'agent-os': ['Requirements with a non-technical creative client', 'Orchestrator and intent-router design', 'Ten specialist agent workflows in n8n', 'Per-agent access scopes', 'Local model setup on Ollama with Docker', 'Training sessions and handover documentation'],
  goecoach: ['Platform architecture (Next.js, FastAPI, Supabase)', 'Multi-LLM routing across GPT-4, Claude and Gemini', 'RAG memory with pgvector HNSW and Redis', 'SMS, email and voice automation flows', 'Zero-downtime Airtable to Supabase migration', 'Production operations and stability'],
  'voice-agent': ['Lead enrichment pipeline', 'LLM sentiment and intent classification', 'Vapi voice agent conversation design', 'Calendar booking during the call', 'TCPA-aware calling flow', 'CRM logging and reporting'],
  'welfare-hr': ['Process audit of HR operations', 'End-to-end automation blueprint', 'AI screening and summary design', 'Human approval checkpoints', 'Scheduling, offer and onboarding automations', 'Team coaching and enablement'],
  levelup: ['Registration portal frontend', 'Deployment to Vercel and Azure Container Apps', 'Fault-tolerant CSV ingestion engine', 'Deterministic certificate ID scheme', 'Two-tier RAG search', 'Sprint delivery in Jira and Confluence'],
  'a-square-merch': ['Site concept, information architecture and UI direction', 'Custom 3D coverflow carousel and techniques accordion', 'GSAP and Lenis scroll-driven intro', 'Prisma schema, seed script and data-access layer', 'Admin CMS and role-gated API routes', 'RFQ pipeline, SQLite to Postgres move, and Vercel deployment'],
  selvenza: ['Problem discovery with the QA team', 'DOM snapshot diffing engine', 'Selector-matching and healing logic', 'Automated test refactoring', 'Node.js backend and REST APIs', 'GitHub Actions and Docker integration'],
};
