// Hand-built product mockups (pure HTML/CSS). Each returns a fixed-size scene; site.js scales it to fit.
const phone = (inner, cls = '') => `<div class="phone ${cls}"><div class="scr"><div class="notch"></div><div class="sb"><span>9:41</span><span>●●● ▮</span></div>${inner}</div></div>`;
const win = (url, body, w = 620) => `<div class="win" style="width:${w}px"><div class="win-bar"><i></i><i></i><i></i><span>${url}</span></div><div class="win-body">${body}</div></div>`;
const fcard = (label, value, sub) => `<div class="float-card"><small>${label}</small><b>${value}</b><span class="up">${sub}</span></div>`;

export const mockups = {
  sopbot: () => `<div class="mk stack-layout">
    <div class="callcard">
      <div class="av">📞</div><b>SOPBot Line</b><small>Recording · 04:12</small>
      <div class="wave"></div>
      <div class="transcript">
        <p><b>OPS</b>"When a new client signs, first we create the folder, then…"</p>
        <p><b>AI</b>Detected trigger, 3 tools, 7 steps, 2 edge cases</p>
      </div>
    </div>
    <div class="stack-col">
      ${win('docs.google.com / SOP-014 Client Onboarding', `<div class="doc">
        <h6>Client Onboarding</h6><div class="dmeta">SOP-014 · Generated by SOPBot · Owner: Operations</div>
        <div class="dsec">Purpose</div><div>Set up every new client consistently within one business day.</div>
        <div class="dsec">Trigger</div><div>Contract signed in CRM</div>
        <div class="dsec">Steps</div>
        <ol><li>Create client folder from template <i>(Google Drive)</i></li><li>Send welcome email and intake form <i>(Gmail)</i></li><li>Schedule kickoff call <i>(Calendar)</i></li></ol>
        <div class="edge"><b>Edge case:</b> Client has no signed NDA. Pause, then route to Legal.</div>
      </div>`, 500)}
      ${win('workflowiq / report', `<table class="scoretable">
        <tr><th>Process</th><th>Automation score</th><th>Tool</th></tr>
        <tr><td>Client onboarding</td><td><div class="meter"><i style="width:92%"></i></div></td><td><span class="pill">n8n</span></td></tr>
        <tr><td>Invoice follow-up</td><td><div class="meter"><i style="width:78%"></i></div></td><td><span class="pill g">Zapier</span></td></tr>
        <tr><td>Weekly reporting</td><td><div class="meter"><i style="width:64%"></i></div></td><td><span class="pill">LLM</span></td></tr>
      </table>`, 500)}
    </div>
  </div>`,

  'exotic-lobby': () => `<div class="mk phones">
    ${phone(`<div class="el-screen"><small style="font-size:10px;color:var(--gold);letter-spacing:.14em">CONVOY · RIYADH RUN</small>
      <div class="el-msg in"><small>Khalid · SF90</small>Fuel stop in 20 km, regroup at exit 14</div>
      <div class="el-msg in"><small>Marco · 296 GTB</small>Copy. Two cars behind me</div>
      <div class="el-msg out">Route updated for everyone ✓</div>
      <div class="el-msg in"><small>Event bot</small>Dinner at 21:00, valet confirmed 🏁</div></div>`)}
    ${phone(`<div class="el-map"><svg viewBox="0 0 240 520"><defs><linearGradient id="rt" x1="0" x2="1"><stop offset="0" stop-color="#F1D9A2"/><stop offset="1" stop-color="#6EF0C2"/></linearGradient></defs>
      <g stroke="#1E232C" stroke-width="1">${Array.from({ length: 14 }, (_, i) => `<line x1="0" y1="${i * 40}" x2="240" y2="${i * 40 + 60}"/><line x1="${i * 24}" y1="0" x2="${i * 24 - 40}" y2="520"/>`).join('')}</g>
      <path d="M30 470 C 60 380, 170 400, 150 300 S 60 200, 120 120 S 210 60, 200 40" fill="none" stroke="url(#rt)" stroke-width="4" stroke-linecap="round"/>
      <path class="flowdash" d="M30 470 C 60 380, 170 400, 150 300 S 60 200, 120 120 S 210 60, 200 40" fill="none" stroke="#fff" stroke-width="1.5" opacity=".6"/>
      <circle cx="150" cy="300" r="7" fill="#D8B774"/><circle cx="150" cy="300" r="16" fill="#D8B774" opacity=".2"/>
      <circle cx="118" cy="140" r="6" fill="#6EF0C2"/><circle cx="60" cy="400" r="6" fill="#9D8CFF"/></svg>
      <div class="el-top"><small>Live · 12 cars</small><b>Dubai → Hatta Mountain Drive</b></div>
      <div class="el-bottom">
        <div class="el-car"><i></i><div>Ferrari SF90<br><span>Lead · 82 km/h</span></div><em>● live</em></div>
        <div class="el-car"><i style="background:linear-gradient(135deg,#6EF0C2,#1d5c49)"></i><div>McLaren 765LT<br><span>0.8 km behind</span></div><em>● live</em></div>
      </div></div>`)}
    ${phone(`<div class="el-screen"><div class="el-h">My Garage</div>
      <span class="el-chip">3 cars</span><span class="el-chip">Service due: 1</span>
      <div class="el-garage"><div class="ph"></div><div>Lamborghini Revuelto<span>Service booked · Tue 10:00</span></div></div>
      <div class="el-garage"><div class="ph" style="filter:hue-rotate(160deg)"></div><div>Porsche 918 Spyder<span>Next event: Yas Marina</span></div></div></div>`)}
  </div>`,

  'agent-os': () => {
    const names = ['Scheduling', 'Research', 'Script & notes', 'Email & comms', 'Budget', 'Production docs', 'Knowledge base', 'Travel', 'Social & PR', 'Admin'];
    const cx = 280, cy = 250, R = 205;
    const pts = names.map((n, i) => { const a = -Math.PI / 2 + i * 2 * Math.PI / names.length; return { n, x: cx + R * Math.cos(a), y: cy + R * 0.92 * Math.sin(a) }; });
    return `<div class="mk agraph"><svg viewBox="0 0 560 520">
      <circle cx="${cx}" cy="${cy}" r="120" fill="none" stroke="#2A2A35" stroke-dasharray="2 6"/>
      ${pts.map(p => `<line x1="${cx}" y1="${cy}" x2="${p.x}" y2="${p.y}" stroke="#34343F"/><line class="flowdash" x1="${cx}" y1="${cy}" x2="${p.x}" y2="${p.y}" stroke="#D8B774" stroke-opacity=".55"/>`).join('')}
    </svg>
    <div class="anode core" style="left:${cx}px;top:${cy}px"><small>ORCHESTRATOR</small>Master Intent Router</div>
    ${pts.map(p => `<div class="anode" style="left:${p.x}px;top:${p.y}px"><i></i>${p.n}</div>`).join('')}
    <div class="anode lock">🔒 Local-first · Ollama · data never leaves the machine</div></div>`;
  },

  goecoach: () => `<div class="mk stack-layout">
    ${phone(`<div class="sms-head"><i></i><b>Coach · GoeCoach</b></div><div class="sms-body">
      <div class="bub-time">Today 7:02 AM</div>
      <div class="bub them">Morning, Alex. Yesterday you committed to closing the hiring plan. Did it happen?</div>
      <div class="bub me">Half done. Got pulled into investor calls</div>
      <div class="bub them">Noted. That's the 3rd week investor calls ate your deep work. Want to block 9–11 as no-meeting time?</div>
      <div class="bub me">Yes, do it</div>
      <div class="typing"><i></i><i></i><i></i></div></div>`, 'sms')}
    <div class="stack-col">${fcard('RAG latency', '&lt;500ms', 'pgvector HNSW + Redis')}${fcard('Automated touchpoints', '448+', 'email · SMS · voice')}${fcard('Model router', '3 LLMs', 'GPT-4 · Claude · Gemini')}</div>
  </div>`,

  'voice-agent': () => `<div class="mk stack-layout">
    <div class="callcard" style="width:300px">
      <div class="av">🤖</div><b>AI Sales Agent</b><small>Outbound · Live call 01:47</small>
      <div class="wave"></div>
      <div class="transcript">
        <p><b>AI</b>Would Thursday at 3 PM work for a 20-minute walkthrough?</p>
        <p><b>LEAD</b>Thursday works, yes.</p>
        <p><b>SENTIMENT</b>Positive · high intent</p>
      </div>
      <div class="booked">✓ Meeting booked on the calendar during the call</div>
    </div>
    <div class="stack-col">${fcard('Leads enriched / day', '100+', 'LLM scored')}${fcard('Compliance', 'TCPA', 'consent-aware dialing')}${fcard('Booking', 'Mid-call', 'no human handoff')}</div>
  </div>`,

  'welfare-hr': () => win('hr-automation / blueprint', `<div class="pipeline">
    <div class="pl-col"><small>Screening <b>AI</b></small><div class="pl-card ai">CV parsed + scored<span>● auto-shortlisted</span></div><div class="pl-card ai">Role-fit summary<span>● LLM generated</span></div><div class="pl-card">Manual review<span>HR approves</span></div></div>
    <div class="pl-col"><small>Scheduling</small><div class="pl-card ai">Slots offered<span>● auto via calendar</span></div><div class="pl-card">Interview panel<span>2 confirmed</span></div></div>
    <div class="pl-col"><small>Offer</small><div class="pl-card ai">Offer letter drafted<span>● template + data</span></div><div class="pl-card">Manager sign-off<span>human in the loop</span></div></div>
    <div class="pl-col"><small>Onboarding</small><div class="pl-card ai">Welcome pack sent<span>● automated</span></div><div class="pl-card ai">Docs checklist<span>● reminders</span></div></div>
  </div>`, 760),

  levelup: () => win('levelup-northeast / admin', `<div class="kpi-row">
      <div class="kpi"><small>Registrations</small><b>5,000+</b></div>
      <div class="kpi"><small>Corrupted rows</small><b style="color:var(--mint)">0</b></div>
      <div class="kpi"><small>Certificate IDs</small><b>64-bit</b></div></div>
    <div class="bars">${[22, 30, 26, 40, 48, 44, 60, 72, 66, 88, 96, 100, 84, 70].map(h => `<i style="height:${h}%"></i>`).join('')}</div>
    <div class="ingest">$ ingest athletes.csv --dry-run<br><span class="ok">✓</span> 4,812 rows valid · <span class="w">!</span> 17 malformed rows recovered<br><span class="ok">✓</span> concurrency lock acquired · commit ok · 0 rows lost</div>`, 640),

  selvenza: () => `<div class="mk stack-layout">${win('selvenza / heal-report', `<div class="code">
      <div class="cm">// checkout.spec.ts: selector drift detected by DOM snapshot diff</div>
      <div><span class="k">await</span> page.click(</div>
      <div class="del">-   <span class="s">'#btn-submit-order'</span></div>
      <div class="add">+   <span class="s">'[data-testid="place-order"]'</span></div>
      <div>);</div>
      <div class="cm">// confidence 0.97 · matched by role, text and position</div>
      <div><span class="k">expect</span>(page).toHaveURL(<span class="s">/confirmation/</span>);</div>
    </div>`, 560)}
    <div class="stack-col">${fcard('QA time saved', '40+ hrs', 'per release')}${fcard('Pipeline', 'CI/CD', 'GitHub Actions')}</div></div>`,
};
